plugins {
	id 'java'
	id 'org.springframework.boot' version '3.5.12'
	id 'io.spring.dependency-management' version '1.1.7'
	id 'com.diffplug.spotless' version '6.25.0'
	id 'nu.studer.jooq' version '9.0'
}

group = 'com.followMe'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
}

configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}
}

repositories {
	mavenLocal()
	mavenCentral()
	maven {
		url "https://maven.pkg.github.com/8ollowMe/common-lib"
		credentials {
			username = findProperty("gpr.user")
			password = findProperty("gpr.key")
		}
	}
}

ext {
	set('springCloudVersion', "2025.0.1")
}

dependencyManagement {
	imports {
		mavenBom "org.springframework.cloud:spring-cloud-dependencies:${springCloudVersion}"
	}
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-web'
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	implementation 'org.springframework.boot:spring-boot-starter-validation'
	implementation 'org.jooq:jooq'
	implementation 'org.springframework.boot:spring-boot-starter-jooq'
	compileOnly 'org.projectlombok:lombok'
	runtimeOnly 'org.postgresql:postgresql'
	annotationProcessor 'org.projectlombok:lombok'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'

	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

	implementation 'org.springframework.cloud:spring-cloud-starter-netflix-eureka-client'
	implementation 'org.springframework.cloud:spring-cloud-starter-openfeign'
	implementation 'org.springframework.cloud:spring-cloud-starter-circuitbreaker-resilience4j'
	implementation 'org.springframework.cloud:spring-cloud-starter-config'
	implementation 'org.springframework.cloud:spring-cloud-starter-bootstrap'

	implementation 'com.followMe:common-lib:1.0.7'
	implementation 'org.springframework.kafka:spring-kafka'
	implementation 'org.springframework.boot:spring-boot-starter-actuator'
	implementation 'io.micrometer:micrometer-tracing-bridge-brave'
	implementation 'io.zipkin.reporter2:zipkin-reporter-brave'

	jooqGenerator 'org.postgresql:postgresql'
	jooqGenerator 'org.jooq:jooq:3.19.30'
	jooqGenerator 'org.jooq:jooq-meta:3.19.30'
	jooqGenerator 'org.jooq:jooq-codegen:3.19.30'
}

sourceSets {
	main {
		java {
			srcDirs 'src/generated/jooq'
		}
	}
}

tasks.named('test') {
	useJUnitPlatform()
}

jooq {
	configurations {
		main {
			generationTool {
				jdbc {
					driver = 'org.postgresql.Driver'
					url = 'jdbc:postgresql://localhost:5432/followme'
					user = 'followme'
					password = 'followme'
				}
				generator {
					name = 'org.jooq.codegen.DefaultGenerator'
					database {
						name = 'org.jooq.meta.postgres.PostgresDatabase'
						inputSchema = 'delivery'
						includes = 'p_delivery|p_shipment'
					}
					target {
						packageName = 'com.followMe.delivery_server.jooq'
						directory = 'src/generated/jooq'
					}
				}
			}
		}
	}
}

spotless {
	java {
		googleJavaFormat('1.24.0')
		target 'src/**/*.java'
	}
}
