spring:
  application:
    name: delivery-server
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
    consumer:
      group-id: delivery-server
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"


  config:
    import: "optional:configserver:"

  cloud:
    config:
      uri: http://localhost:13100
      fail-fast: false
    openfeign:
      okhttp:
        enabled: true

  datasource:
    url: jdbc:postgresql://localhost:5432/followme
    username: ${DB_USERNAME:followme}
    password: ${DB_PASSWORD:followme}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_batch_fetch_size: 100
        default_schema: delivery

  jooq:
    sql-dialect: POSTGRES

feign:
  circuitbreaker:
    enabled: true

resilience4j:
  circuitbreaker:
    instances:
      hub-server:
        failure-rate-threshold: 50          # 회로 차단 기준
        minimum-number-of-calls: 5          # 최소 통계 횟수
        sliding-window-size: 10             # 최근 호출 기준 개수
        wait-duration-in-open-state: 10s    # 차단 후 복구 시도까지 대기 시간
        permitted-number-of-calls-in-half-open-state: 3  # 복구 시도 시 허용되는 호출 수

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

---
spring:
  config:
    activate:
      on-profile: local

  kafka:
    properties:
      security.protocol: SSL
      ssl.truststore.location: classpath:kafka.truststore.jks
      ssl.truststore.password: ${KAFKA_TRUSTSTORE_PASSWORD}
      ssl.endpoint.identification.algorithm: ""

---
spring:
  config:
    activate:
      on-profile: prod

  kafka:
    bootstrap-servers: 172.31.10.105:9092,172.31.1.110:9092,172.31.15.248:9092
    properties:
      security.protocol: SSL
      ssl.truststore.location: /etc/kafka/ssl/kafka.server.truststore.jks
      ssl.truststore.password: ${KAFKA_TRUSTSTORE_PASSWORD}
      ssl.endpoint.identification.algorithm: ""

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true